
name: xmw_shop
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  common_utils: ^1.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluintl: ^0.1.3

  cupertino_icons: ^0.1.3
  rxdart: ^0.22.6
  flukit: ^1.0.2
  azlistview: ^0.1.1
  fluttertoast: ^3.0.1
  pull_to_refresh: ^1.5.0
  shared_preferences: ^0.5.0
  #get_ip: ^0.3.0
  dio: ^3.0.8
  http: ^0.12.0 #latest version
  flutter_easyrefresh: ^2.1.0
  transparent_image: ^0.1.0
  cached_network_image: ^2.0.0-rc
  #share: ^0.6.1+1
  event_bus: ^1.1.0 #eventbus
  image_picker: ^0.6.5 #选择照片吗
  bot_toast: ^2.4.0
  multi_image_picker: ^4.6.1
  flutter_image_compress: ^0.6.8
  fluwx_no_pay: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
        - assets/images/guide1.png
        - assets/images/tab_service.png
        - assets/images/tab_service_s.png
        - assets/images/tab_quote.png
        - assets/images/tab_quote_s.png
        - assets/images/tab_trade.png
        - assets/images/tab_trade_s.png
        - assets/images/tab_find.png
        - assets/images/tab_find_s.png
        - assets/images/tab_my.png
        - assets/images/tab_my_s.png
        - assets/images/icon_service_1.png
        - assets/images/radio_default_cover.png
        - assets/images/open_bank_arrow.png
        - assets/images/icon_back.png
        - assets/images/icon_message.png
        - assets/images/icon_favorited.png
        - assets/images/shanchu.png
        - assets/images/update_icon.png
        - assets/images/invitation_detial_bg.png
        - assets/images/icon_plus.png
        - assets/images/icon_query.png
        - assets/images/ic_quote_share.png
        - assets/images/cancel_white.png
        - assets/images/ic_quote_detail_more.png
        - assets/images/bg_subscript.png
        - assets/images/icon_finance_news.png
        - assets/images/gold_bg.png
        - assets/images/gold_hint.png
        - assets/images/del_his_img.png
        - assets/images/home_logo.png
        - assets/images/home_title_search.png
        - assets/images/home_notice_img.png
        - assets/images/home_more_img.png
        - assets/images/home_sort_ccq.png
        - assets/images/home_sort_cmos.png
        - assets/images/home_sort_dcdc.png
        - assets/images/home_sort_dsp.png
        - assets/images/home_sort_fpga.png
        - assets/images/home_sort_sjzhq.png
        - assets/images/home_sort_wclq.png
        - assets/images/home_sort_zxkzq.png
        - assets/images/home_service_tel.png
        - assets/images/home_service_wx.png
        - assets/images/my_arrow_right.png
        - assets/images/my_img_price.png
        - assets/images/my_img_message.png
        - assets/images/my_img_history.png
        - assets/images/my_img_gold.png
        - assets/images/my_img_collect.png
        - assets/images/my_img_attention.png
        - assets/images/title_msg_img.png
        - assets/images/invitation_collect.png
        - assets/images/invitation_msg.png
        - assets/images/bom_title_add.png
        - assets/images/bom_default_img.png
        - assets/images/detail_collect.png
        - assets/images/detail_collect_s.png
        - assets/images/detail_getsample.png
        - assets/images/product_down.png
        - assets/images/product_share.png
        - assets/images/product_zan.png
        - assets/images/detail_star.png
        - assets/images/product_handbook.png
        - assets/images/prodect_list_add.png
        - assets/images/prodect_list_addhas.png
        - assets/images/prodect_list_down.png
        - assets/images/login_logo.png
        - assets/images/invitation_back.png
        - assets/images/detail_manufacturers.png
        - assets/images/head_default_pic.png
        - assets/images/invitation_collect_s.png
        - assets/images/zan_img.png
        - assets/images/zan_s_img.png
        - assets/images/banner_img.png
        - assets/images/sort_perch.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages